name: Trigger auto deployment for java-app-formation

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/java-app-formation-AutoDeployTrigger-1654d108-9428-4199-96c1-6c03e80a9e3b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: abderrezak.azurecr.io
          username: ${{ secrets.JAVAAPPFORMATION_REGISTRY_USERNAME }}
          password: ${{ secrets.JAVAAPPFORMATION_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: abderrezak.azurecr.io/java-app-formation:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JAVAAPPFORMATION_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n java-app-formation -g javaApp --server abderrezak.azurecr.io --username  ${{ secrets.JAVAAPPFORMATION_REGISTRY_USERNAME }} --password ${{ secrets.JAVAAPPFORMATION_REGISTRY_PASSWORD }}
            az containerapp update -n java-app-formation -g javaApp --image abderrezak.azurecr.io/java-app-formation:${{ github.sha }}
